// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4iCPRGhZJIvRzzm6W0YXtSNbh4GwLhr0',
    appId: '1:292049482602:web:6abd61e47cbfac762cab13',
    messagingSenderId: '292049482602',
    projectId: 'chat-app-3008e',
    authDomain: 'chat-app-3008e.firebaseapp.com',
    storageBucket: 'chat-app-3008e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbt0RzLOvuqQNMiHEJN6i179-FYLxltsw',
    appId: '1:292049482602:android:6070ec7eda3377d32cab13',
    messagingSenderId: '292049482602',
    projectId: 'chat-app-3008e',
    storageBucket: 'chat-app-3008e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvcLKrHhOU-U6wHiNfkSVO3NwCBkm72_I',
    appId: '1:292049482602:ios:aac73484707dc7782cab13',
    messagingSenderId: '292049482602',
    projectId: 'chat-app-3008e',
    storageBucket: 'chat-app-3008e.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvcLKrHhOU-U6wHiNfkSVO3NwCBkm72_I',
    appId: '1:292049482602:ios:aac73484707dc7782cab13',
    messagingSenderId: '292049482602',
    projectId: 'chat-app-3008e',
    storageBucket: 'chat-app-3008e.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4iCPRGhZJIvRzzm6W0YXtSNbh4GwLhr0',
    appId: '1:292049482602:web:6d9a871436bbc35b2cab13',
    messagingSenderId: '292049482602',
    projectId: 'chat-app-3008e',
    authDomain: 'chat-app-3008e.firebaseapp.com',
    storageBucket: 'chat-app-3008e.firebasestorage.app',
  );
}
